// 全局配置参数
const config = {
  appName: '自定义表单|掌控云',
  // 环境变量
  env: process.env.NODE_ENV,
  domain: 'http://115.28.151.114:9335',
  testDomain: 'http://115.28.151.114:9335',
  // 是否开启console打印
  showConsole: process.env.NODE_ENV === 'development' ? true : false,
  iconList: [
    require('../assets/img/icon/icon(1).png'),
    require('../assets/img/icon/icon(2).png'),
    require('../assets/img/icon/icon(3).png'),
    require('../assets/img/icon/icon(4).png'),
    require('../assets/img/icon/icon(5).png'),
    require('../assets/img/icon/icon(6).png'),
    require('../assets/img/icon/icon(7).png'),
    require('../assets/img/icon/icon(8).png'),
    require('../assets/img/icon/icon(9).png'),
    require('../assets/img/icon/icon(10).png'),
    require('../assets/img/icon/icon(11).png'),
    require('../assets/img/icon/icon(12).png'),
    require('../assets/img/icon/icon(13).png'),
    require('../assets/img/icon/icon(14).png'),
    require('../assets/img/icon/icon(15).png'),
    require('../assets/img/icon/icon(16).png'),
    require('../assets/img/icon/icon(17).png'),
    require('../assets/img/icon/icon(18).png'),
    require('../assets/img/icon/icon(19).png'),
    require('../assets/img/icon/icon(20).png'),
    require('../assets/img/icon/icon(21).png'),
    require('../assets/img/icon/icon(22).png'),
    require('../assets/img/icon/icon(23).png'),
    require('../assets/img/icon/icon(24).png'),
    require('../assets/img/icon/icon(25).png'),
    require('../assets/img/icon/icon(26).png'),
    require('../assets/img/icon/icon(27).png'),
    require('../assets/img/icon/icon(28).png'),
    require('../assets/img/icon/icon(29).png'),
    require('../assets/img/icon/icon(30).png'),
    require('../assets/img/icon/icon(31).png'),
    require('../assets/img/icon/icon(32).png'),
    require('../assets/img/icon/icon(33).png'),
    require('../assets/img/icon/icon(34).png'),
    require('../assets/img/icon/icon(35).png'),
    require('../assets/img/icon/icon(36).png'),
    require('../assets/img/icon/icon(37).png'),
    require('../assets/img/icon/icon(38).png'),
    require('../assets/img/icon/icon(39).png'),
    require('../assets/img/icon/icon(40).png'),
    require('../assets/img/icon/icon(41).png'),
    require('../assets/img/icon/icon(42).png'),
    require('../assets/img/icon/icon(43).png'),
    require('../assets/img/icon/icon(44).png'),
    require('../assets/img/icon/icon(45).png'),
    require('../assets/img/icon/icon(46).png'),
    require('../assets/img/icon/icon(47).png'),
    require('../assets/img/icon/icon(48).png'),
    require('../assets/img/icon/icon(49).png'),
    require('../assets/img/icon/icon(50).png'),
    require('../assets/img/icon/icon(51).png'),
    require('../assets/img/icon/icon(52).png'),
    require('../assets/img/icon/icon(53).png')
  ]
}

export default config
